USE [master]
GO

/****** Object:  Database [repAnalysis]    Script Date: 27/06/2018 20:42:23 ******/
CREATE DATABASE [repAnalysis]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'repAnalysis', FILENAME = N'C:\Databases\Data\repAnalysis.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'repAnalysis_log', FILENAME = N'C:\Databases\Data\repAnalysis_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [repAnalysis] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [repAnalysis].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [repAnalysis] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [repAnalysis] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [repAnalysis] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [repAnalysis] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [repAnalysis] SET ARITHABORT OFF 
GO

ALTER DATABASE [repAnalysis] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [repAnalysis] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [repAnalysis] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [repAnalysis] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [repAnalysis] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [repAnalysis] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [repAnalysis] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [repAnalysis] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [repAnalysis] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [repAnalysis] SET  DISABLE_BROKER 
GO

ALTER DATABASE [repAnalysis] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [repAnalysis] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [repAnalysis] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [repAnalysis] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [repAnalysis] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [repAnalysis] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [repAnalysis] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [repAnalysis] SET RECOVERY FULL 
GO

ALTER DATABASE [repAnalysis] SET  MULTI_USER 
GO

ALTER DATABASE [repAnalysis] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [repAnalysis] SET DB_CHAINING OFF 
GO

ALTER DATABASE [repAnalysis] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [repAnalysis] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [repAnalysis] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [repAnalysis] SET QUERY_STORE = OFF
GO

USE [repAnalysis]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [repAnalysis] SET  READ_WRITE 
GO

